name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: 1//0gaSIchkU_qA2CgYIARAAGBASNwF-L9IrWNOpRuzT8wOu-TuvTVnczCOxrxh-01IIOiEQxf8E4WDOqSS6PTZ7_t-mRCNuWg7TeXI
